# Generated by Django 3.1.3 on 2021-02-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20210209_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:15 - 3:15', '2:15 - 3:15'), ('3:15 - 4:15', '3:15 - 4:15')], default='11:00 - 11:50', max_length=50),
        ),
    ]
