# Generated by Django 3.1.3 on 2021-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210209_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:15 - 3:15', '2:15 - 3:15'), ('3:15 - 4:15', '3:15 - 4:15')], default='11:30 - 12:30', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-2-10'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('CIE 1', 'CIE 1'), ('CIE 2', 'CIE 2'), ('CIE 3', 'CIE 3'), ('Lab Internal', 'Lab Internal'), ('Lab External', 'Lab External'), ('SEE theory', 'SEE theory')], default='CIE 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('CIE 1', 'CIE 1'), ('CIE 2', 'CIE 2'), ('CIE 3', 'CIE 3'), ('Lab Internal', 'Lab Internal'), ('Lab External', 'Lab External'), ('SEE theory', 'SEE theory')], default='CIE 1', max_length=50),
        ),
    ]
